foreach(required SDK_DIR FIXTURE_DIR TEST_ROOT HOST_CONSUMER CXX_COMPILER)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing SDK contract input: ${required}")
    endif()
endforeach()
if(NOT BUILD_CONFIG)
    set(BUILD_CONFIG Debug)
endif()
set(generator_args)
if(GENERATOR)
    list(APPEND generator_args -G "${GENERATOR}")
endif()
if(GENERATOR_PLATFORM)
    list(APPEND generator_args -A "${GENERATOR_PLATFORM}")
endif()
if(GENERATOR_TOOLSET)
    list(APPEND generator_args -T "${GENERATOR_TOOLSET}")
endif()
file(MAKE_DIRECTORY "${TEST_ROOT}/source")
file(COPY "${FIXTURE_DIR}/" DESTINATION "${TEST_ROOT}/source")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_ROOT}/source" -B "${TEST_ROOT}/build"
    ${generator_args}
    "-DHoroEngineGameplay_DIR=${SDK_DIR}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}" "-DCMAKE_BUILD_TYPE=${BUILD_CONFIG}"
    RESULT_VARIABLE configured)
if(NOT configured EQUAL 0)
    message(FATAL_ERROR "External Physics SDK configure failed: ${configured}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_ROOT}/build" --config "${BUILD_CONFIG}"
    --target HoroPhysicsSdkModule --parallel 2 RESULT_VARIABLE built)
if(NOT built EQUAL 0)
    message(FATAL_ERROR "External Physics SDK module build failed: ${built}")
endif()
file(READ "${TEST_ROOT}/build/artifact-${BUILD_CONFIG}.txt" artifact)
file(READ "${TEST_ROOT}/build/HoroPhysicsSdkModule_generated_behavior_bundle.revision" revision)
string(STRIP "${revision}" revision)
execute_process(COMMAND "${HOST_CONSUMER}" "${artifact}" "${revision}" RESULT_VARIABLE activated)
if(NOT activated EQUAL 0)
    message(FATAL_ERROR "External Physics SDK module activation failed: ${activated}")
endif()
