# The executable and fixture paths come only from CTest's generated target configuration.
foreach(required ENGINE MODULE REVISION_FILE SOURCE_ROOT PHYSICS_NATIVE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing CTest launch fixture input: ${required}")
    endif()
endforeach()
if(NOT IS_ABSOLUTE "${ENGINE}" OR NOT EXISTS "${ENGINE}")
    message(FATAL_ERROR "CTest must supply its absolute built engine target")
endif()
file(READ "${REVISION_FILE}" revision LIMIT 128)
string(STRIP "${revision}" revision)
set(script "${SOURCE_ROOT}/tests/fixtures/gameplay_physics/PhysicsContext.horo_script")

function(expect_launch expected count kind first second third permission)
    # Quote each fixed argument independently: empty identities must reach the real parser.
    if(count EQUAL 4)
        execute_process(COMMAND "${ENGINE}" --run-network-product standalone 2
            "${kind}" "${first}" "${second}" "${third}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    elseif(count EQUAL 6)
        execute_process(COMMAND "${ENGINE}" --run-network-product standalone 2
            "${kind}" "${first}" "${second}" "${third}" "${permission}" extra
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    else()
        execute_process(COMMAND "${ENGINE}" --run-network-product standalone 2
            "${kind}" "${first}" "${second}" "${third}" "${permission}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    endif()
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "Launch ${kind} returned ${result}, expected ${expected}: ${output}${error}")
    endif()
    if(expected EQUAL 0)
        if(NOT output MATCHES "network product completed 2 frames")
            message(FATAL_ERROR "Missing success receipt: ${output}${error}")
        endif()
    elseif(NOT error MATCHES "horo-engine:")
        message(FATAL_ERROR "Missing failure diagnostic: ${output}${error}")
    endif()
endfunction()

expect_launch(2 5 --unknown "${MODULE}" game.tests "${revision}" grant)
expect_launch(2 5 --game-module "${MODULE}" game.tests "${revision}" implicit)
expect_launch(2 5 --game-module relative.so game.tests "${revision}" grant)
foreach(invalid_revision 0 bad 1tail 18446744073709551616)
    expect_launch(2 5 --game-module "${MODULE}" game.tests "${invalid_revision}" grant)
endforeach()
expect_launch(2 5 --game-script relative.horo_script "${script}.meta" game.tests grant)
expect_launch(2 5 --game-script "${script}" relative.meta game.tests grant)
expect_launch(2 4 --game-module "${MODULE}" game.tests "${revision}" grant)
expect_launch(2 6 --game-module "${MODULE}" game.tests "${revision}" grant)
# OFF must reject startup rather than silently select another solver.
if(PHYSICS_NATIVE)
    set(expected 0)
else()
    set(expected 3)
endif()
foreach(permission grant deny)
    expect_launch(${expected} 5 --game-module "${MODULE}" game.tests "${revision}" "${permission}")
    expect_launch(${expected} 5 --game-script "${script}" "${script}.meta" game.tests "${permission}")
endforeach()
expect_launch(3 5 --game-script "${script}.missing" "${script}.meta" game.tests grant)
expect_launch(3 5 --game-module "${MODULE}" "" "${revision}" grant)
expect_launch(3 5 --game-script "${script}" "${script}.meta" "" grant)
message(STATUS "18 production gameplay launch cases passed")
