if(NOT EXISTS "${VALIDATOR}")
    message(FATAL_ERROR "The extension manifest validator was not staged in the SDK")
endif()
if(NOT EXISTS "${CONFORMANCE}")
    message(FATAL_ERROR "The extension ABI conformance harness was not staged in the SDK")
endif()
if(NOT EXISTS "${SCHEMA}")
    message(FATAL_ERROR "The extension manifest schema was not staged in the SDK")
endif()
file(READ "${SCHEMA}" schema_contents)
string(JSON schema_version GET "${schema_contents}" properties schemaVersion const)
if(NOT schema_version EQUAL 1)
    message(FATAL_ERROR "The packaged extension manifest schema is not V1")
endif()
