if(NOT HORO_ENGINE_SOURCE_DIR)
    message(FATAL_ERROR "HORO_ENGINE_SOURCE_DIR is required")
endif()

list(APPEND CMAKE_MODULE_PATH "${HORO_ENGINE_SOURCE_DIR}/cmake")
include(HoroDependencyDirection)
include(HoroDependencyPolicy)

function(require_audio_policy target expected)
    string(SHA256 key "${target}")
    get_property(declared GLOBAL PROPERTY "HORO_DEPENDENCY_POLICY_${key}" SET)
    if(NOT declared)
        message(FATAL_ERROR "Audio dependency policy is missing ${target}")
    endif()
    get_property(actual GLOBAL PROPERTY "HORO_DEPENDENCY_POLICY_${key}")
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Audio dependency policy for ${target} is '${actual}', expected '${expected}'")
    endif()
endfunction()

require_audio_policy(HoroAudioSafetyHooks "")
require_audio_policy(HoroAudioMemory "HoroAudioApi;HoroAudioSafetyHooks")
require_audio_policy(HoroAudioCommands "HoroAudioMemory;HoroAudioSafetyHooks")
require_audio_policy(HoroAudioMixer "HoroAudioDsp;HoroAudioCommands")
require_audio_policy(HoroAudioWatchdog "HoroAudioBackendContract;HoroAudioSafetyHooks")
