#pragma once

/**
 * @file UpdateZipStagingJob.h
 * @brief Host worker operation from HTTPS update download to verified ZIP stage.
 */

#include "Horo/Release/UpdateFileDelta.h"
#include "Horo/Release/UpdateHttpDownload.h"
#include "Horo/Release/UpdateStageReady.h"

namespace Horo::Release {
    /** @brief Immutable paths and policies for one HTTPS-to-ZIP staging operation. */
    struct UpdateZipStagingRequest final {
        const UpdatePackageRecord &package;
        const UpdateDownloadPaths &paths;
        const std::filesystem::path &stageRoot;
        const UpdateDownloadLimits &downloadLimits;
        const UpdateArchiveLimits &archiveLimits;
        UpdateHttpDownloadPolicy policy{};
    };

    /**
     * @brief Downloads or resumes a signed ZIP, then publishes an exact private stage.
     * @param request Authenticated package, private paths, absent stage, and resource policies.
     * @param files Native durable filesystem kept alive for the whole operation.
     * @param verifier Trusted publisher signature verifier.
     * @param cancellation Cooperative cancellation token.
     * @param progress Optional callback after durable download progress.
     * @return Durable ready marker, or failure without publishing one.
     * @note The host dispatches this blocking operation on a worker and keeps its
     * private directory quiescent. A complete durable checkpoint skips the network
     * while still rechecking the signed package before extraction.
     */
    [[nodiscard]] Result<std::filesystem::path> PrepareZipUpdateStageHttps(const UpdateZipStagingRequest &request,
                                                                           NativeDurableFileSystem &files,
                                                                           const Security::ArtifactVerifier &verifier,
                                                                           CancellationToken cancellation,
                                                                           const UpdateDownloadProgress &progress = {});

    /** @brief Private reconstructed tree and absent durable destinations for exact signed full-ZIP materialization. */
    struct RepackedDeltaZipRequest final {
        const UpdatePackageRecord &fullPackage;
        const UpdateFileDeltaPlan &plan;
        const std::filesystem::path &stageRoot;
        const std::filesystem::path &packageFile;
        const std::filesystem::path &checkpointFile;
        const UpdateArchiveLimits &limits;
    };

    /** @brief Complete signed full-package checkpoint and durable ready marker after local ZIP reproduction. */
    struct RepackedDeltaZipResult final {
        UpdateTransferCheckpoint checkpoint;
        std::filesystem::path readyMarker;
    };

    /**
     * @brief Repackages a verified delta reconstruction as the exact signed full ZIP before publishing ready.
     * @param request Allowed signed full package, target plan, private stage, absent package/checkpoint paths, and limits.
     * @param files Durable filesystem retained for the transaction.
     * @param verifier Publisher verifier for the full package's signed byte identity.
     * @param cancellation Cooperative cancellation before ready publication.
     * @return Complete checkpoint and ready marker only if generated bytes equal the signed full package.
     * @note A byte mismatch fails closed; the caller may then discard its owned stage and fetch the allowed full package.
     */
    [[nodiscard]] Result<RepackedDeltaZipResult> RepackVerifiedDeltaAsFullZip(const RepackedDeltaZipRequest &request,
                                                                              NativeDurableFileSystem &files,
                                                                              const Security::ArtifactVerifier &verifier,
                                                                              CancellationToken cancellation);

    /** @brief Signed full package plus optional delta and private inputs for one bounded ZIP delivery attempt. */
    struct SelectedZipStagingRequest final {
        const UpdatePackageCandidates &candidates;
        const std::filesystem::path &baseRoot;
        std::span<const UpdateStagedFile> baseInventory;
        std::span<const UpdateStagedFile> targetInventory;
        const UpdateDownloadPaths &deltaPaths;
        const std::filesystem::path &deltaStageRoot;
        const UpdateDownloadPaths &fullPaths;
        const std::filesystem::path &stageRoot;
        const UpdateDownloadLimits &downloadLimits;
        const UpdateArchiveLimits &archiveLimits;
        UpdateHttpDownloadPolicy policy{};
    };

    /** @brief Complete signed full-package evidence regardless of which transfer path succeeded. */
    struct SelectedZipStagingResult final {
        UpdateTransferCheckpoint checkpoint;
        std::filesystem::path readyMarker;
        bool usedDelta{};
    };

    /**
     * @brief Tries an authenticated delta once, then automatically fetches the allowed signed full ZIP on failure.
     * @param request Authenticated candidates, verified base and target inventories, disjoint private paths, and bounds.
     * @param files Durable filesystem retained for the complete attempt.
     * @param verifier Publisher verifier for delta and full bytes.
     * @param cancellation Cooperative cancellation; never triggers full fallback after cancellation.
     * @param progress Optional durable download progress callback.
     * @return A regular full-ZIP ready stage and checkpoint, with the delivery route reported separately.
     * @note The caller authenticates candidates via SelectUpdatePackageCandidates and keeps source trees quiescent.
     * @note On delta success the caller retains ownership of deltaStageRoot and may remove it after activation evidence is recorded.
     */
    [[nodiscard]] Result<SelectedZipStagingResult> PrepareSelectedZipUpdateStageHttps(const SelectedZipStagingRequest &request,
                                                                                      NativeDurableFileSystem &files,
                                                                                      const Security::ArtifactVerifier &verifier,
                                                                                      CancellationToken cancellation,
                                                                                      const UpdateDownloadProgress &progress = {});
}  // namespace Horo::Release
