import { lazy, Suspense, useState } from 'react';
import { WorkspaceIcon } from './WorkspaceIcon';
import { releaseActivity, releaseStages, type ReleaseJob } from '../releaseJob';
const WorkspaceViewport = lazy(() => import('./WorkspaceViewport').then(module => ({ default: module.WorkspaceViewport })));
import './workspace.css';

const docks = ['Assets', 'Console', 'Build', 'Ops', 'MCP', 'Perf', 'Physics', 'Audio', 'Net'] as const;
type Dock = typeof docks[number];
const releaseId = 'architecture/release/release-modal-design.html';
const menus: Record<string, { label: string; design?: string; dock?: Dock; message?: string }[]> = {
  File: [{ label: 'New Scene', message: 'New Scene' }, { label: 'Open Project', message: 'Open Project' }, { label: 'Save Scene', message: 'Scene saved' }, { label: 'Project Settings', design: 'architecture/editor/project-settings.html' }, { label: 'Editor Settings', design: 'architecture/editor/settings-modal.html' }],
  Edit: [{ label: 'Undo', message: 'Undo' }, { label: 'Redo', message: 'Redo' }, { label: 'Duplicate', message: 'Duplicate object' }, { label: 'Delete', message: 'Delete object' }],
  Assets: [{ label: 'Asset Browser', design: 'architecture/editor/asset-browser.html' }, { label: 'Import Assets', dock: 'Assets' }, { label: 'Refresh Assets', dock: 'Assets' }],
  GameObject: [{ label: 'Create Empty', message: 'Create Empty' }, { label: 'Create 3D Object', message: 'Create 3D Object' }, { label: 'Frame Selected', message: 'Frame Selected' }],
  Component: [{ label: 'Add Component', message: 'Add Component' }, { label: 'Transform', message: 'Transform' }, { label: 'Renderer', message: 'Renderer' }],
  Window: [{ label: 'Console', dock: 'Console' }, { label: 'Build', dock: 'Build' }, { label: 'Operations', dock: 'Ops' }, { label: 'Performance', dock: 'Perf' }, { label: 'Physics Debugger', design: 'architecture/runtime/physics-debugger.html' }, { label: 'Audio Mixer', design: 'architecture/runtime/audio-mixer.html' }],
  Build: [{ label: 'Build & Release', design: releaseId }, { label: 'Build Output', design: 'architecture/runtime/build-output.html' }, { label: 'Build Diagnostics', dock: 'Build' }],
  Help: [{ label: 'About Horo Editor', message: 'Horo Editor 0.1.0' }, { label: 'Documentation', message: 'Documentation' }, { label: 'Keyboard Shortcuts', message: 'Keyboard Shortcuts' }],
};

function DockContent({ tab, releaseJob }: { tab: Dock; releaseJob: ReleaseJob | null }) {
  if (tab === 'Assets') return <>
    <div className="ws-dock-tools"><span>‹</span><span>›</span><span>↑</span><b>assets</b><input placeholder="⌕  Search assets…" /><button>All types ⌄</button><button>Name ⌄</button><button className="accent">＋ Import</button></div>
    <div className="ws-assets"><div className="ws-asset-rail">☆<br />◴<br />☷<br />▣</div><div className="ws-folder-grid">{['materials', 'Meshes', 'models', 'scenes', 'scripts', 'shaders', 'textures'].map((item, index) => <div key={item} className={index === 1 ? 'selected' : ''}><div className="ws-folder-icon"><WorkspaceIcon name="folder" size={26} /></div><span>{item}</span><small>{index === 1 || index === 3 ? '1 item' : '0 items'}</small></div>)}</div></div>
  </>;
  if (tab === 'Console') return <>
    <div className="ws-dock-tools"><input placeholder="⌕  Search logs…" /><button className="outlined">All 19</button><button>ⓘ Info 19</button><button>⚠ Warnings 0</button><button>⊗ Errors 0</button><button>All sources ⌄</button><button>☑ Auto-scroll</button><button>Clear</button></div>
    <div className="ws-table ws-console-table"><div className="head"><span>Time</span><span>Level</span><span>Source</span><span>Message</span></div>{['Observability runtime initialised', 'Host identity snapshot', 'Process started', 'Platform: Linux'].map(message => <div key={message}><span>12:07:14</span><span className="info">ⓘ Info</span><span>Observability</span><span>{message}</span></div>)}</div>
  </>;
  if (tab === 'Build') return <><div className="ws-dock-tools"><input placeholder="⌕  Search diagnostics…" /><button className="outlined">All 0</button><button>Errors 0</button><button>Warnings 0</button><button>Editor ⌄</button><button>Development ⌄</button><button className="outlined">◴ Rebuild</button></div><div className="ws-table"><div className="head"><span>Level</span><span>Line</span><span>File</span><span>Message</span></div></div></>;
  if (tab === 'Ops') return <><div className="ws-dock-tools"><input placeholder="⌕  Search operations…" /><button className="outlined">All</button><button>Running {releaseJob?.status === 'running' ? 1 : 0}</button><button>Failed 0</button><button>All types ⌄</button><button>Cancel all</button></div><div className="ws-table"><div className="head"><span>Operation</span><span>Status</span><span>Progress</span><span>Elapsed / Action</span></div>{releaseJob && <div><span>Build &amp; Release</span><span className={releaseJob.status === 'success' ? 'ws-job-done' : 'info'}>{releaseJob.status === 'running' ? releaseStages[releaseJob.stageIndex].label : releaseJob.status === 'success' ? 'Completed' : 'Cancelled'}</span><span>{releaseJob.status === 'success' ? '100%' : `${Math.round((releaseJob.stageIndex / releaseStages.length) * 100)}%`}</span><span>{releaseActivity(releaseJob)}</span></div>}</div></>;
  if (tab === 'MCP') return <><div className="ws-dock-tools"><input placeholder="⌕  Search tool calls…" /><button className="outlined">All 18</button><button>Mutations 3</button><button>Errors 1</button><button>Current session ⌄</button><button>Pause</button><button>Export audit</button></div><div className="ws-table"><div className="head"><span>Time</span><span>Tool</span><span>Permission</span><span>Request / Status</span></div>{[['12:08:14', 'scene.query', 'Read', 'query: selected objects · Done'], ['12:08:08', 'asset.list', 'Read', 'path: assets/textures · Done'], ['12:07:51', 'scene.move', 'Mutation', 'PF Enemy → (2.4, 0, 1.2) · Approval']].map(row => <div key={row[0]}>{row.map(cell => <span key={cell}>{cell}</span>)}</div>)}</div></>;
  if (tab === 'Perf') return <><div className="ws-dock-tools"><input placeholder="⌕  Search counters…" /><button>Last 10 seconds ⌄</button><button>All subsystems ⌄</button><button className="outlined">Live</button><button className="outlined">Capture</button></div><div className="ws-metrics">{[['Frame time · p95', '16.7 ms'], ['CPU frame', '4.1 ms'], ['GPU frame', '15.8 ms'], ['Process memory', '628 MB']].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value}</strong><i /></div>)}</div></>;
  if (tab === 'Physics') return <><div className="ws-dock-tools"><input placeholder="⌕  Search bodies and shapes…" /><button>World · Room ⌄</button><button className="outlined">Colliders</button><button className="outlined">Contacts</button><button>Constraints</button><button>Pause</button></div><div className="ws-metrics">{[['Physics step', '0.72 ms'], ['Active / sleeping', '28 / 64'], ['Contacts / pairs', '14 / 37'], ['Snapshot buffer', '8 / 16']].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div><div className="ws-table"><div className="head"><span>Body</span><span>State</span><span>Shape</span><span>Timing / contacts</span></div>{[['Player','Active','Capsule','4 contacts · 0.11 ms'],['PF Enemy','Active','Convex','2 contacts · 0.08 ms'],['Floor 000','Static','Mesh','8 contacts · broadphase BVH']].map(row => <div key={row[0]}>{row.map(cell => <span key={cell}>{cell}</span>)}</div>)}</div></>;
  if (tab === 'Audio') return <><div className="ws-dock-tools"><input placeholder="⌕  Search busses and voices…" /><button>Default output ⌄</button><button className="outlined">Meters</button><button>Voices</button><button>Pause</button><button>Mute all</button></div><div className="ws-metrics">{[['Master peak', '−3.2 dB'], ['Voices', '12 / 64'], ['Callback budget', '0.31 ms'], ['Underruns', '0']].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div><div className="ws-audio">{['Master','Music','SFX','Ambient'].map((name, index) => <div key={name}><span>{name}</span><span>{index === 0 ? '0.0' : '−6.0'} dB</span><i style={{ width: `${78 - index * 10}%` }} /><span>{[12,2,7,3][index]}</span><button>M</button><button>S</button></div>)}</div></>;
  return <><div className="ws-dock-tools"><input placeholder="⌕  Search connections and messages…" /><button>Current session ⌄</button><button className="outlined">Connections</button><button>Queues</button><button>Trace</button><button>Pause capture</button></div><div className="ws-metrics">{[['RTT · p95','42 ms'],['Receive','12.3 kb/s'],['Send','3.1 kb/s'],['Packet loss','0.2%']].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div><div className="ws-table"><div className="head"><span>Connection</span><span>State</span><span>RTT</span><span>Queues / backpressure</span></div>{[['local-server:7777','Open','42 ms','RPC 0 · reliable 2 · no drops'],['editor-presence','Open','18 ms','events 1 / 128 · coalescing'],['asset-sync','Idle','—','bounded queue · drop-oldest']].map(row => <div key={row[0]}>{row.map(cell => <span key={cell}>{cell}</span>)}</div>)}</div></>;
}

export function WorkspaceDesign({ openDesign, releaseJob }: { openDesign: (id: string) => void; releaseJob: ReleaseJob | null }) {
  const [dock, setDock] = useState<Dock>('Assets');
  const [menu, setMenu] = useState<string | null>(null);
  const [selection, setSelection] = useState('Box');
  const [inspectorTab, setInspectorTab] = useState<'Inspector' | 'Scene'>('Inspector');
  const [notice, setNotice] = useState('');

  const runMenuAction = (action: (typeof menus)[string][number]) => {
    setMenu(null);
    if (action.design) openDesign(action.design);
    if (action.dock) setDock(action.dock);
    if (action.message) setNotice(action.message);
  };

  return <div className="workspace-design">
    <div className="ws-title">Horo Editor <span>−　□　×</span></div>
    <div className="ws-menu"><span className="ws-logo">⬡</span>{Object.entries(menus).map(([name, actions]) => <div key={name} className="ws-menu-item"><button onClick={() => setMenu(menu === name ? null : name)} aria-expanded={menu === name}>{name}</button>{menu === name && <div className="ws-menu-popup">{actions.map(action => <button key={action.label} onClick={() => runMenuAction(action)}>{action.label}</button>)}</div>}</div>)}<span className="ws-version">Horo Engine 0.1.0</span></div>
    <div className="ws-workarea">
      <div className="ws-rail"><button aria-label="Hierarchy" title="Hierarchy"><WorkspaceIcon name="panel" size={19} /></button><button aria-label="Scene" title="Scene"><WorkspaceIcon name="scene" size={19} /></button><button aria-label="Search" title="Search"><WorkspaceIcon name="search" size={19} /></button><button aria-label="Settings" title="Settings" onClick={() => openDesign('architecture/editor/settings-modal.html')}><WorkspaceIcon name="settings" size={19} /></button><button className="ws-rail-bottom" aria-label="Console" title="Console" onClick={() => setDock('Console')}><WorkspaceIcon name="terminal" size={21} /></button></div>
      <aside className="ws-hierarchy"><div className="ws-panel-tab">Hierarchy</div><div className="ws-panel-tools"><button aria-label="Add object" title="Add object" onClick={() => setNotice('Add object')}><WorkspaceIcon name="plus" /></button><div className="ws-panel-actions"><button aria-label="Filter objects" title="Filter objects"><WorkspaceIcon name="filter" size={16} /></button><button aria-label="Sort objects" title="Sort objects"><WorkspaceIcon name="sort" size={16} /></button><button aria-label="More hierarchy options" title="More hierarchy options"><WorkspaceIcon name="more" size={16} /></button></div></div><input placeholder="Search objects…" /><button className="ws-object" onClick={() => setSelection('Box')}><WorkspaceIcon name="box" size={15} />{selection}<span><WorkspaceIcon name="eye" size={16} /><WorkspaceIcon name="lock" size={15} /></span></button><div className="ws-drop">Drop to scene root</div></aside>
      <section className="ws-viewport"><Suspense fallback={<div className="ws-viewport-scene"><div className="ws-grid"><div className="ws-cube" /></div></div>}><WorkspaceViewport /></Suspense><div className="ws-panel-tab">Viewport</div><div className="ws-viewport-toolbar"><button className="ws-select">Perspective <WorkspaceIcon name="chevron" size={14} /></button><button className="ws-select">Shaded <WorkspaceIcon name="chevron" size={14} /></button>{(['grid','select','move','rotate','scale','frame'] as const).map((icon, index) => <button key={icon} className={`ws-tool ${index < 2 ? 'selected' : ''}`} aria-label={icon} title={icon}><WorkspaceIcon name={icon} size={19} /></button>)}</div><div className="ws-axis">Y<br />╋<br />Z</div><span className="ws-object-count">1 object(s)</span></section>
      <aside className="ws-inspector"><div className="ws-inspector-tabs"><button className={inspectorTab === 'Inspector' ? 'active' : ''} onClick={() => setInspectorTab('Inspector')}>Inspector</button><button className={inspectorTab === 'Scene' ? 'active' : ''} onClick={() => setInspectorTab('Scene')}>Scene</button></div>{inspectorTab === 'Inspector' && <><div className="ws-inspector-object"><WorkspaceIcon name="box" size={17} /><input aria-label="Object name" value={selection} onChange={event => setSelection(event.target.value)} /><button aria-label="More object options" title="More object options"><WorkspaceIcon name="more" size={17} /></button></div><div className="ws-transform"><div>⌄　Transform <span>◴　☑　⚙</span></div>{['Position','Rotation','Scale'].map(label => <div className="ws-vector" key={label}><span>{label}</span><em className="axis-x">X</em><input readOnly value={label === 'Scale' ? '1.00' : '0.00'} /><em className="axis-y">Y</em><input readOnly value={label === 'Scale' ? '1.00' : '0.00'} /><em className="axis-z">Z</em><input readOnly value={label === 'Scale' ? '1.00' : '0.00'} /></div>)}</div><button className="ws-add-component">＋ Add Component</button></>}</aside>
    </div>
    <div className="ws-dock"><nav>{docks.map(item => <button key={item} className={dock === item ? 'active' : ''} onClick={() => { setDock(item); setMenu(null); }}>{item}</button>)}</nav><div className="ws-dock-body"><DockContent tab={dock} releaseJob={releaseJob} /></div></div>
    <div className="ws-status"><span className="ws-saved">● Saved</span><span>Sel 1 obj</span><span>Nav idle</span>{releaseJob?.background && <button type="button" className={`ws-job-status ${releaseJob.status}`} onClick={() => openDesign(releaseId)} title="Open Build & Release"><span className="ws-job-indicator" aria-hidden="true" /><span>{releaseActivity(releaseJob)}</span><span className="ws-job-progress">{releaseJob.status === 'running' ? `${Math.round(((releaseJob.stageIndex + 0.5) / releaseStages.length) * 100)}%` : releaseJob.status === 'success' ? '100%' : ''}</span></button>}{notice && <span className="ws-notice">{notice}</span>}<span className="ws-renderer">● OpenGL</span></div>
  </div>;
}
