import { workflowActivity, type WorkflowJob } from '../workflowJob';

export function WorkflowActivity({ job, onBackground, onCancel, onNew, onClose }: { job: WorkflowJob; onBackground: () => void; onCancel: () => void; onNew: () => void; onClose: () => void }) {
  const running = job.status === 'running';
  const completed = job.status === 'success';
  return <div className="release-design release-active">
    <div className="release-stages" style={{ gridTemplateColumns: `repeat(${job.stages.length}, minmax(85px, 1fr))` }}>{job.stages.map((stage, index) => <div key={`${index}-${stage.label}`} className={completed || index < job.stageIndex ? 'done' : index === job.stageIndex && running ? 'current' : ''}><i /><span>{String(index + 1).padStart(2, '0')} {stage.label}</span></div>)}</div>
    <div className="release-summary"><span className={`release-pill ${completed ? 'success' : ''}`}><i />{completed ? 'COMPLETED' : running ? job.stages[job.stageIndex].label.toUpperCase() : 'CANCELLED'}</span><div><small>Target</small><strong>{job.target}</strong></div><div className="release-candidate"><small>{job.kind === 'publish' ? 'Destination' : 'Output'}</small><strong>{job.output}</strong></div></div>
    <main className="release-content"><p className={`release-notice ${completed ? 'release-notice-success' : ''}`}>{completed ? `${job.title} completed in this interactive mock. No files were written or uploaded.` : `Mock job #${String(job.id).slice(-5)} ${running ? 'is running' : 'was cancelled'}. Closing this window keeps its history in Workspace.`}</p><div className="release-log">{job.stages.slice(0, completed ? job.stages.length : job.stageIndex).map((stage, index) => <div key={`${index}-${stage.label}`}><time>{String(index * 2).padStart(2, '0')}s</time><b>{stage.label.toUpperCase()}</b><span>{stage.log}</span></div>)}{running && <div className="release-log-current"><time>{String(job.stageIndex * 2).padStart(2, '0')}s</time><b>{job.stages[job.stageIndex].label.toUpperCase()}</b><span><i aria-hidden="true" />{workflowActivity(job)}</span></div>}{completed && <div className="release-log-success"><time>✓</time><b>SUCCESS</b><span>{job.title} completed</span></div>}</div></main>
    <footer className="release-footer"><div className={`release-operation ${completed ? 'completed' : ''}`} role="status" aria-live="polite">{running && <i aria-hidden="true" />}{workflowActivity(job)}</div><div className="release-actions">{running ? <><button type="button" className="danger" onClick={onCancel}>Cancel job</button><button type="button" className="primary" onClick={onBackground}>Keep running in background</button></> : <><button type="button" onClick={onNew}>New job</button><button type="button" className="primary" onClick={onClose}>Close</button></>}</div></footer>
  </div>;
}
