file(READ "${MANIFEST}" _links)
if(_links MATCHES "NetworkTransportGNS|GameNetworkingSockets|SteamNetworkingSockets")
    message(FATAL_ERROR "${PROFILE} profile links a production transport: ${_links}")
endif()
if(PROFILE STREQUAL "Disabled")
    if(_links MATCHES "Horo(NetworkApi|NetworkRuntime|NetworkTransportNull)|HoroEngine::Network(Api|Runtime|TransportNull)")
        message(FATAL_ERROR "Disabled profile links networking: ${_links}")
    endif()
elseif(PROFILE STREQUAL "Null")
    if(NOT _links MATCHES "HoroEngine::NetworkRuntime" OR
       NOT _links MATCHES "HoroEngine::NetworkTransportNull")
        message(FATAL_ERROR "Headless Null profile is missing its explicit backend links: ${_links}")
    endif()
else()
    message(FATAL_ERROR "Unknown network linkage profile: ${PROFILE}")
endif()
