# Host paths are supplied only through the environment, never recorded in package metadata.
if(NOT DEFINED ENV{ANDROID_NDK_ROOT} OR "$ENV{ANDROID_NDK_ROOT}" STREQUAL "")
    message(FATAL_ERROR "Android preflight: set ANDROID_NDK_ROOT to NDK 28.2.13676358")
endif()
file(READ "$ENV{ANDROID_NDK_ROOT}/source.properties" _horo_ndk_properties)
if(NOT _horo_ndk_properties MATCHES "Pkg.Revision[ \t]*=[ \t]*28[.]2[.]13676358([\r\n]|$)")
    message(FATAL_ERROR "Android preflight: install the pinned NDK 28.2.13676358")
endif()
if(NOT DEFINED ENV{HORO_ANDROID_ABI} OR NOT "$ENV{HORO_ANDROID_ABI}" MATCHES "^(arm64-v8a|x86_64)$")
    message(FATAL_ERROR "Android preflight: HORO_ANDROID_ABI must select arm64-v8a or x86_64; configure each ABI independently")
endif()
set(ANDROID_ABI "$ENV{HORO_ANDROID_ABI}" CACHE STRING "Declared Android ABI")
set(ANDROID_PLATFORM android-29 CACHE STRING "Android API floor")
set(ANDROID_STL c++_shared CACHE STRING "One shared C++ runtime per package ABI")
set(ANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES ON CACHE BOOL "16 KiB-compatible native ELF alignment")
include("$ENV{ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake")
