#include "Horo/Runtime/Ui/UiErrors.h"
#include "UiDiagnosticsInternal.h"

#include <array>

namespace Horo::Runtime::Ui::Detail {
    namespace {
        const std::array descriptors{
            &UiErrors::IdentityInvalid,
            &UiErrors::OwnershipGenerationInvalid,
            &UiErrors::HandleMalformed,
            &UiErrors::HandleOwnerMismatch,
            &UiErrors::HandleStale,
            &UiErrors::RevisionInvalid,
            &UiErrors::RevisionStale,
            &UiErrors::GenerationExhausted,
            &UiErrors::DocumentInvalid,
            &UiErrors::DocumentDuplicateIdentity,
            &UiErrors::DependencyInvalid,
            &UiErrors::CapacityExceeded,
            &UiErrors::PayloadInvalid,
            &UiErrors::CanvasReferenceInvalid,
            &UiErrors::CanvasSpaceInvalid,
            &UiErrors::CanvasSpaceModeMismatch,
            &UiErrors::CanvasSpaceOverflow,
            &UiErrors::InstanceStateInvalid,
            &UiErrors::ElementTreeInvalid,
            &UiErrors::ElementTreeIdentityConflict,
            &UiErrors::StructuralCommandInvalid,
            &UiErrors::StructuralCommandConflict,
            &UiErrors::ElementTreeLifecycleUnavailable,
            &UiErrors::LayoutInvalid,
            &UiErrors::LayoutSourceStale,
            &UiErrors::LayoutNonConvergent,
            &UiErrors::LayoutSnapshotStorageExhausted,
            &UiErrors::LayoutLifecycleUnavailable,
            &UiErrors::HitTestInvalid,
            &UiErrors::HitTestSourceStale,
            &UiErrors::HitTestNotPresented,
            &UiErrors::HitTestSnapshotStorageExhausted,
            &UiErrors::HitTestLifecycleUnavailable,
            &UiErrors::RenderSnapshotInvalid,
            &UiErrors::RenderCommandInvalid,
            &UiErrors::RenderResourceReferenceInvalid,
            &UiErrors::RenderSnapshotStorageExhausted,
            &UiErrors::RenderSnapshotLifecycleUnavailable,
            &UiErrors::RenderGeometryInvalid,
            &UiErrors::RenderGeometryCapacityExceeded,
            &UiErrors::RenderGeometryStorageExhausted,
            &UiErrors::RenderGeometryLifecycleUnavailable,
            &UiErrors::RenderCompositionCapacityExceeded,
            &UiErrors::RenderCompositionInvalid,
            &UiErrors::RenderPresentationInvalid,
            &UiErrors::RenderPresentationStale,
            &UiErrors::EventDispatchInvalid,
            &UiErrors::EventDispatchSourceStale,
            &UiErrors::EventDispatchModalBoundaryViolation,
            &UiErrors::EventDispatchCapacityExceeded,
            &UiErrors::EventDispatchRouteInvalidated,
            &UiErrors::EventDispatchReentrant,
            &UiErrors::EventDispatchHandlerFailed,
            &UiErrors::EventDispatchLifecycleUnavailable,
            &UiErrors::PointerCaptureInvalid,
            &UiErrors::PointerCaptureSourceStale,
            &UiErrors::PointerCaptureInteractionStale,
            &UiErrors::PointerCaptureBusy,
            &UiErrors::PointerCaptureCapacityExceeded,
            &UiErrors::PointerCaptureLifecycleUnavailable,
            &UiErrors::ActionInvalid,
            &UiErrors::ActionPayloadInvalid,
            &UiErrors::ActionPayloadCapacityExceeded,
            &UiErrors::ActionCommandInvalid,
            &UiErrors::ActionQueueCapacityExceeded,
            &UiErrors::ActionSourceStale,
            &UiErrors::ActionResultInvalid,
            &UiErrors::ActionResultStale,
            &UiErrors::ActionHandlerFailed,
            &UiErrors::ActionLifecycleUnavailable,
            &UiErrors::NavigationInvalid,
            &UiErrors::ControlDescriptorInvalid,
            &UiErrors::ControlInputInvalid,
            &UiErrors::ControlSourceStale,
            &UiErrors::ControlDefaultPending,
            &UiErrors::ControlDefaultInvalid,
            &UiErrors::ControlCapacityExceeded,
            &UiErrors::ControlSequenceInvalid,
            &UiErrors::ControlLifecycleUnavailable,
            &UiErrors::FocusInvalid,
            &UiErrors::FocusSourceStale,
            &UiErrors::FocusTargetUnavailable,
            &UiErrors::FocusModalBoundaryViolation,
            &UiErrors::FocusCapacityExceeded,
            &UiErrors::FocusModalCapacityExceeded,
            &UiErrors::FocusModalStale,
            &UiErrors::FocusScopeMismatch,
            &UiErrors::FocusLifecycleUnavailable,
            &UiErrors::DiagnosticInvalid,
            &UiErrors::DiagnosticUnsupported,
        };
    }  // namespace

    std::span<const ErrorCodeDescriptor *const> DiagnosticDescriptors() noexcept {
        return descriptors;
    }
}  // namespace Horo::Runtime::Ui::Detail
