# Host-owned optional transport linkage. Concrete backend targets are never dependencies
# of NetworkApi or NetworkRuntime; only an explicitly composed product may name them.
function(_horo_assert_transport_profile TARGET PROFILE VISITED)
    if("${TARGET}" IN_LIST VISITED)
        return()
    endif()
    list(APPEND VISITED "${TARGET}")
    foreach(_property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(_dependencies "${TARGET}" "${_property}")
        if(NOT _dependencies)
            continue()
        endif()
        foreach(_dependency IN LISTS _dependencies)
            if("${_dependency}" MATCHES "NetworkTransportGNS|GameNetworkingSockets|SteamNetworkingSockets")
                message(FATAL_ERROR "${TARGET} transitively links production transport ${_dependency}")
            endif()
            if(PROFILE STREQUAL "DISABLED" AND
               "${_dependency}" MATCHES "Horo(NetworkApi|NetworkRuntime|NetworkTransportNull)|HoroEngine::Network(Api|Runtime|TransportNull)")
                message(FATAL_ERROR "${TARGET} links network target ${_dependency} in the disabled profile")
            endif()
            if(TARGET "${_dependency}")
                _horo_assert_transport_profile("${_dependency}" "${PROFILE}" "${VISITED}")
            endif()
        endforeach()
    endforeach()
endfunction()

function(horo_configure_network_transport_profile TARGET PROFILE)
    if(NOT TARGET "${TARGET}")
        message(FATAL_ERROR "Unknown network transport composition target: ${TARGET}")
    endif()
    if(PROFILE STREQUAL "DISABLED")
        # The product deliberately has no NetworkRuntime or concrete transport dependency.
    elseif(PROFILE STREQUAL "HEADLESS_NULL")
        target_link_libraries("${TARGET}" PRIVATE HoroEngine::NetworkRuntime HoroEngine::NetworkTransportNull)
    elseif(PROFILE STREQUAL "PRODUCTION_GNS")
        if(NOT TARGET HoroEngine::NetworkTransportGNS)
            message(FATAL_ERROR "Production GNS transport is not installed in this build")
        endif()
        target_link_libraries("${TARGET}" PRIVATE HoroEngine::NetworkRuntime HoroEngine::NetworkTransportGNS)
    else()
        message(FATAL_ERROR "Unknown network transport profile: ${PROFILE}")
    endif()
    if(PROFILE STREQUAL "DISABLED" OR PROFILE STREQUAL "HEADLESS_NULL")
        _horo_assert_transport_profile("${TARGET}" "${PROFILE}" "")
    endif()
endfunction()
